<?php
require_once ("ThePaymentGateway/TPG_Common.php");

$iclISOCountryList = new ISOCountryList();
$iclISOCountryList -> add(826, "GB", "GBR", "United Kingdom", 3);
$iclISOCountryList -> add(840, "US", "USA", "United States", 2);
$iclISOCountryList -> add(36, "AU", "AUS", "Australia", 1);
$iclISOCountryList -> add(124, "CA", "CAN", "Canada", 1);
$iclISOCountryList -> add(276, "DE", "DEU", "Germany", 1);
$iclISOCountryList -> add(250, "FR", "FRA", "France", 1);
$iclISOCountryList -> add(533, "AW", "ABW", "Aruba", 0);
$iclISOCountryList -> add(4, "AF", "AFG", "Afghanistan", 0);
$iclISOCountryList -> add(24, "AO", "AGO", "Angola", 0);
$iclISOCountryList -> add(660, "AI", "AIA", "Anguilla", 0);
$iclISOCountryList -> add(248, "AX", "ALA", "Åland Islands", 0);
$iclISOCountryList -> add(8, "AL", "ALB", "Albania", 0);
$iclISOCountryList -> add(20, "AD", "AND", "Andorra", 0);
$iclISOCountryList -> add(530, "AN", "ANT", "Netherlands Antilles", 0);
$iclISOCountryList -> add(784, "AE", "ARE", "United Arab Emirates", 0);
$iclISOCountryList -> add(32, "AR", "ARG", "Argentina", 0);
$iclISOCountryList -> add(51, "AM", "ARM", "Armenia", 0);
$iclISOCountryList -> add(16, "AS", "ASM", "American Samoa", 0);
$iclISOCountryList -> add(10, "AQ", "ATA", "Antarctica", 0);
$iclISOCountryList -> add(260, "TF", "ATF", "French Southern Territories", 0);
$iclISOCountryList -> add(28, "AG", "ATG", "Antigua and Barbuda", 0);
$iclISOCountryList -> add(40, "AT", "AUT", "Austria", 0);
$iclISOCountryList -> add(31, "AZ", "AZE", "Azerbaijan", 0);
$iclISOCountryList -> add(108, "BI", "BDI", "Burundi", 0);
$iclISOCountryList -> add(56, "BE", "BEL", "Belgium", 0);
$iclISOCountryList -> add(204, "BJ", "BEN", "Benin", 0);
$iclISOCountryList -> add(854, "BF", "BFA", "Burkina Faso", 0);
$iclISOCountryList -> add(50, "BD", "BGD", "Bangladesh", 0);
$iclISOCountryList -> add(100, "BG", "BGR", "Bulgaria", 0);
$iclISOCountryList -> add(48, "BH", "BHR", "Bahrain", 0);
$iclISOCountryList -> add(44, "BS", "BHS", "Bahamas", 0);
$iclISOCountryList -> add(70, "BA", "BIH", "Bosnia and Herzegovina", 0);
$iclISOCountryList -> add(652, "BL", "BLM", "Saint Barthélemy", 0);
$iclISOCountryList -> add(112, "BY", "BLR", "Belarus", 0);
$iclISOCountryList -> add(84, "BZ", "BLZ", "Belize", 0);
$iclISOCountryList -> add(60, "BM", "BMU", "Bermuda", 0);
$iclISOCountryList -> add(68, "BO", "BOL", "Bolivia", 0);
$iclISOCountryList -> add(76, "BR", "BRA", "Brazil", 0);
$iclISOCountryList -> add(52, "BB", "BRB", "Barbados", 0);
$iclISOCountryList -> add(96, "BN", "BRN", "Brunei Darussalam", 0);
$iclISOCountryList -> add(64, "BT", "BTN", "Bhutan", 0);
$iclISOCountryList -> add(74, "BV", "BVT", "Bouvet Island", 0);
$iclISOCountryList -> add(72, "BW", "BWA", "Botswana", 0);
$iclISOCountryList -> add(140, "CF", "CAF", "Central African Republic", 0);
$iclISOCountryList -> add(166, "CC", "CCK", "Cocos (Keeling) Islands", 0);
$iclISOCountryList -> add(756, "CH", "CHE", "Switzerland", 0);
$iclISOCountryList -> add(152, "CL", "CHL", "Chile", 0);
$iclISOCountryList -> add(156, "CN", "CHN", "China", 0);
$iclISOCountryList -> add(384, "CI", "CIV", "Côte d'Ivoire", 0);
$iclISOCountryList -> add(120, "CM", "CMR", "Cameroon", 0);
$iclISOCountryList -> add(180, "CD", "COD", "Congo, the Democratic Republic of the", 0);
$iclISOCountryList -> add(178, "CG", "COG", "Congo", 0);
$iclISOCountryList -> add(184, "CK", "COK", "Cook Islands", 0);
$iclISOCountryList -> add(170, "CO", "COL", "Colombia", 0);
$iclISOCountryList -> add(174, "KM", "COM", "Comoros", 0);
$iclISOCountryList -> add(132, "CV", "CPV", "Cape Verde", 0);
$iclISOCountryList -> add(188, "CR", "CRI", "Costa Rica", 0);
$iclISOCountryList -> add(192, "CU", "CUB", "Cuba", 0);
$iclISOCountryList -> add(162, "CX", "CXR", "Christmas Island", 0);
$iclISOCountryList -> add(136, "KY", "CYM", "Cayman Islands", 0);
$iclISOCountryList -> add(196, "CY", "CYP", "Cyprus", 0);
$iclISOCountryList -> add(203, "CZ", "CZE", "Czech Republic", 0);
$iclISOCountryList -> add(262, "DJ", "DJI", "Djibouti", 0);
$iclISOCountryList -> add(212, "DM", "DMA", "Dominica", 0);
$iclISOCountryList -> add(208, "DK", "DNK", "Denmark", 0);
$iclISOCountryList -> add(214, "DO", "DOM", "Dominican Republic", 0);
$iclISOCountryList -> add(12, "DZ", "DZA", "Algeria", 0);
$iclISOCountryList -> add(218, "EC", "ECU", "Ecuador", 0);
$iclISOCountryList -> add(818, "EG", "EGY", "Egypt", 0);
$iclISOCountryList -> add(232, "ER", "ERI", "Eritrea", 0);
$iclISOCountryList -> add(732, "EH", "ESH", "Western Sahara", 0);
$iclISOCountryList -> add(724, "ES", "ESP", "Spain", 0);
$iclISOCountryList -> add(233, "EE", "EST", "Estonia", 0);
$iclISOCountryList -> add(231, "ET", "ETH", "Ethiopia", 0);
$iclISOCountryList -> add(246, "FI", "FIN", "Finland", 0);
$iclISOCountryList -> add(242, "FJ", "FJI", "Fiji", 0);
$iclISOCountryList -> add(238, "FK", "FLK", "Falkland Islands (Malvinas)", 0);
$iclISOCountryList -> add(234, "FO", "FRO", "Faroe Islands", 0);
$iclISOCountryList -> add(583, "FM", "FSM", "Micronesia, Federated States of", 0);
$iclISOCountryList -> add(266, "GA", "GAB", "Gabon", 0);
$iclISOCountryList -> add(268, "GE", "GEO", "Georgia", 0);
$iclISOCountryList -> add(831, "GG", "GGY", "Guernsey", 0);
$iclISOCountryList -> add(288, "GH", "GHA", "Ghana", 0);
$iclISOCountryList -> add(292, "GI", "GIB", "Gibraltar", 0);
$iclISOCountryList -> add(324, "GN", "GIN", "Guinea", 0);
$iclISOCountryList -> add(312, "GP", "GLP", "Guadeloupe", 0);
$iclISOCountryList -> add(270, "GM", "GMB", "Gambia", 0);
$iclISOCountryList -> add(624, "GW", "GNB", "Guinea-Bissau", 0);
$iclISOCountryList -> add(226, "GQ", "GNQ", "Equatorial Guinea", 0);
$iclISOCountryList -> add(300, "GR", "GRC", "Greece", 0);
$iclISOCountryList -> add(308, "GD", "GRD", "Grenada", 0);
$iclISOCountryList -> add(304, "GL", "GRL", "Greenland", 0);
$iclISOCountryList -> add(320, "GT", "GTM", "Guatemala", 0);
$iclISOCountryList -> add(254, "GF", "GUF", "French Guiana", 0);
$iclISOCountryList -> add(316, "GU", "GUM", "Guam", 0);
$iclISOCountryList -> add(328, "GY", "GUY", "Guyana", 0);
$iclISOCountryList -> add(344, "HK", "HKG", "Hong Kong", 0);
$iclISOCountryList -> add(334, "HM", "HMD", "Heard Island and McDonald Islands", 0);
$iclISOCountryList -> add(340, "HN", "HND", "Honduras", 0);
$iclISOCountryList -> add(191, "HR", "HRV", "Croatia", 0);
$iclISOCountryList -> add(332, "HT", "HTI", "Haiti", 0);
$iclISOCountryList -> add(348, "HU", "HUN", "Hungary", 0);
$iclISOCountryList -> add(360, "ID", "IDN", "Indonesia", 0);
$iclISOCountryList -> add(833, "IM", "IMN", "Isle of Man", 0);
$iclISOCountryList -> add(356, "IN", "IND", "India", 0);
$iclISOCountryList -> add(86, "IO", "IOT", "British Indian Ocean Territory", 0);
$iclISOCountryList -> add(372, "IE", "IRL", "Ireland", 0);
$iclISOCountryList -> add(364, "IR", "IRN", "Iran, Islamic Republic of", 0);
$iclISOCountryList -> add(368, "IQ", "IRQ", "Iraq", 0);
$iclISOCountryList -> add(352, "IS", "ISL", "Iceland", 0);
$iclISOCountryList -> add(376, "IL", "ISR", "Israel", 0);
$iclISOCountryList -> add(380, "IT", "ITA", "Italy", 0);
$iclISOCountryList -> add(388, "JM", "JAM", "Jamaica", 0);
$iclISOCountryList -> add(832, "JE", "JEY", "Jersey", 0);
$iclISOCountryList -> add(400, "JO", "JOR", "Jordan", 0);
$iclISOCountryList -> add(392, "JP", "JPN", "Japan", 0);
$iclISOCountryList -> add(398, "KZ", "KAZ", "Kazakhstan", 0);
$iclISOCountryList -> add(404, "KE", "KEN", "Kenya", 0);
$iclISOCountryList -> add(417, "KG", "KGZ", "Kyrgyzstan", 0);
$iclISOCountryList -> add(116, "KH", "KHM", "Cambodia", 0);
$iclISOCountryList -> add(296, "KI", "KIR", "Kiribati", 0);
$iclISOCountryList -> add(659, "KN", "KNA", "Saint Kitts and Nevis", 0);
$iclISOCountryList -> add(410, "KR", "KOR", "Korea, Republic of", 0);
$iclISOCountryList -> add(414, "KW", "KWT", "Kuwait", 0);
$iclISOCountryList -> add(418, "LA", "LAO", "Lao People's Democratic Republic", 0);
$iclISOCountryList -> add(422, "LB", "LBN", "Lebanon", 0);
$iclISOCountryList -> add(430, "LR", "LBR", "Liberia", 0);
$iclISOCountryList -> add(434, "LY", "LBY", "Libyan Arab Jamahiriya", 0);
$iclISOCountryList -> add(662, "LC", "LCA", "Saint Lucia", 0);
$iclISOCountryList -> add(438, "LI", "LIE", "Liechtenstein", 0);
$iclISOCountryList -> add(144, "LK", "LKA", "Sri Lanka", 0);
$iclISOCountryList -> add(426, "LS", "LSO", "Lesotho", 0);
$iclISOCountryList -> add(440, "LT", "LTU", "Lithuania", 0);
$iclISOCountryList -> add(442, "LU", "LUX", "Luxembourg", 0);
$iclISOCountryList -> add(428, "LV", "LVA", "Latvia", 0);
$iclISOCountryList -> add(446, "MO", "MAC", "Macao", 0);
$iclISOCountryList -> add(663, "MF", "MAF", "Saint Martin (French part)", 0);
$iclISOCountryList -> add(504, "MA", "MAR", "Morocco", 0);
$iclISOCountryList -> add(492, "MC", "MCO", "Monaco", 0);
$iclISOCountryList -> add(498, "MD", "MDA", "Moldova", 0);
$iclISOCountryList -> add(450, "MG", "MDG", "Madagascar", 0);
$iclISOCountryList -> add(462, "MV", "MDV", "Maldives", 0);
$iclISOCountryList -> add(484, "MX", "MEX", "Mexico", 0);
$iclISOCountryList -> add(584, "MH", "MHL", "Marshall Islands", 0);
$iclISOCountryList -> add(807, "MK", "MKD", "Macedonia, the former Yugoslav Republic of", 0);
$iclISOCountryList -> add(466, "ML", "MLI", "Mali", 0);
$iclISOCountryList -> add(470, "MT", "MLT", "Malta", 0);
$iclISOCountryList -> add(104, "MM", "MMR", "Myanmar", 0);
$iclISOCountryList -> add(499, "ME", "MNE", "Montenegro", 0);
$iclISOCountryList -> add(496, "MN", "MNG", "Mongolia", 0);
$iclISOCountryList -> add(580, "MP", "MNP", "Northern Mariana Islands", 0);
$iclISOCountryList -> add(508, "MZ", "MOZ", "Mozambique", 0);
$iclISOCountryList -> add(478, "MR", "MRT", "Mauritania", 0);
$iclISOCountryList -> add(500, "MS", "MSR", "Montserrat", 0);
$iclISOCountryList -> add(474, "MQ", "MTQ", "Martinique", 0);
$iclISOCountryList -> add(480, "MU", "MUS", "Mauritius", 0);
$iclISOCountryList -> add(454, "MW", "MWI", "Malawi", 0);
$iclISOCountryList -> add(458, "MY", "MYS", "Malaysia", 0);
$iclISOCountryList -> add(175, "YT", "MYT", "Mayotte", 0);
$iclISOCountryList -> add(516, "NA", "NAM", "Namibia", 0);
$iclISOCountryList -> add(540, "NC", "NCL", "New Caledonia", 0);
$iclISOCountryList -> add(562, "NE", "NER", "Niger", 0);
$iclISOCountryList -> add(574, "NF", "NFK", "Norfolk Island", 0);
$iclISOCountryList -> add(566, "NG", "NGA", "Nigeria", 0);
$iclISOCountryList -> add(558, "NI", "NIC", "Nicaragua", 0);
$iclISOCountryList -> add(570, "NU", "NIU", "Niue", 0);
$iclISOCountryList -> add(528, "NL", "NLD", "Netherlands", 0);
$iclISOCountryList -> add(578, "NO", "NOR", "Norway", 0);
$iclISOCountryList -> add(524, "NP", "NPL", "Nepal", 0);
$iclISOCountryList -> add(520, "NR", "NRU", "Nauru", 0);
$iclISOCountryList -> add(554, "NZ", "NZL", "New Zealand", 0);
$iclISOCountryList -> add(512, "OM", "OMN", "Oman", 0);
$iclISOCountryList -> add(586, "PK", "PAK", "Pakistan", 0);
$iclISOCountryList -> add(591, "PA", "PAN", "Panama", 0);
$iclISOCountryList -> add(612, "PN", "PCN", "Pitcairn", 0);
$iclISOCountryList -> add(604, "PE", "PER", "Peru", 0);
$iclISOCountryList -> add(608, "PH", "PHL", "Philippines", 0);
$iclISOCountryList -> add(585, "PW", "PLW", "Palau", 0);
$iclISOCountryList -> add(598, "PG", "PNG", "Papua New Guinea", 0);
$iclISOCountryList -> add(616, "PL", "POL", "Poland", 0);
$iclISOCountryList -> add(630, "PR", "PRI", "Puerto Rico", 0);
$iclISOCountryList -> add(408, "KP", "PRK", "Korea, Democratic People's Republic of", 0);
$iclISOCountryList -> add(620, "PT", "PRT", "Portugal", 0);
$iclISOCountryList -> add(600, "PY", "PRY", "Paraguay", 0);
$iclISOCountryList -> add(275, "PS", "PSE", "Palestinian Territory, Occupied", 0);
$iclISOCountryList -> add(258, "PF", "PYF", "French Polynesia", 0);
$iclISOCountryList -> add(634, "QA", "QAT", "Qatar", 0);
$iclISOCountryList -> add(638, "RE", "REU", "Réunion", 0);
$iclISOCountryList -> add(642, "RO", "ROU", "Romania", 0);
$iclISOCountryList -> add(643, "RU", "RUS", "Russian Federation", 0);
$iclISOCountryList -> add(646, "RW", "RWA", "Rwanda", 0);
$iclISOCountryList -> add(682, "SA", "SAU", "Saudi Arabia", 0);
$iclISOCountryList -> add(736, "SD", "SDN", "Sudan", 0);
$iclISOCountryList -> add(686, "SN", "SEN", "Senegal", 0);
$iclISOCountryList -> add(702, "SG", "SGP", "Singapore", 0);
$iclISOCountryList -> add(239, "GS", "SGS", "South Georgia and the South Sandwich Islands", 0);
$iclISOCountryList -> add(654, "SH", "SHN", "Saint Helena", 0);
$iclISOCountryList -> add(744, "SJ", "SJM", "Svalbard and Jan Mayen", 0);
$iclISOCountryList -> add(90, "SB", "SLB", "Solomon Islands", 0);
$iclISOCountryList -> add(694, "SL", "SLE", "Sierra Leone", 0);
$iclISOCountryList -> add(222, "SV", "SLV", "El Salvador", 0);
$iclISOCountryList -> add(674, "SM", "SMR", "San Marino", 0);
$iclISOCountryList -> add(706, "SO", "SOM", "Somalia", 0);
$iclISOCountryList -> add(666, "PM", "SPM", "Saint Pierre and Miquelon", 0);
$iclISOCountryList -> add(688, "RS", "SRB", "Serbia", 0);
$iclISOCountryList -> add(678, "ST", "STP", "Sao Tome and Principe", 0);
$iclISOCountryList -> add(740, "SR", "SUR", "Suriname", 0);
$iclISOCountryList -> add(703, "SK", "SVK", "Slovakia", 0);
$iclISOCountryList -> add(705, "SI", "SVN", "Slovenia", 0);
$iclISOCountryList -> add(752, "SE", "SWE", "Sweden", 0);
$iclISOCountryList -> add(748, "SZ", "SWZ", "Swaziland", 0);
$iclISOCountryList -> add(690, "SC", "SYC", "Seychelles", 0);
$iclISOCountryList -> add(760, "SY", "SYR", "Syrian Arab Republic", 0);
$iclISOCountryList -> add(796, "TC", "TCA", "Turks and Caicos Islands", 0);
$iclISOCountryList -> add(148, "TD", "TCD", "Chad", 0);
$iclISOCountryList -> add(768, "TG", "TGO", "Togo", 0);
$iclISOCountryList -> add(764, "TH", "THA", "Thailand", 0);
$iclISOCountryList -> add(762, "TJ", "TJK", "Tajikistan", 0);
$iclISOCountryList -> add(772, "TK", "TKL", "Tokelau", 0);
$iclISOCountryList -> add(795, "TM", "TKM", "Turkmenistan", 0);
$iclISOCountryList -> add(626, "TL", "TLS", "Timor-Leste", 0);
$iclISOCountryList -> add(776, "TO", "TON", "Tonga", 0);
$iclISOCountryList -> add(780, "TT", "TTO", "Trinidad and Tobago", 0);
$iclISOCountryList -> add(788, "TN", "TUN", "Tunisia", 0);
$iclISOCountryList -> add(792, "TR", "TUR", "Turkey", 0);
$iclISOCountryList -> add(798, "TV", "TUV", "Tuvalu", 0);
$iclISOCountryList -> add(158, "TW", "TWN", "Taiwan, Province of China", 0);
$iclISOCountryList -> add(834, "TZ", "TZA", "Tanzania, United Republic of", 0);
$iclISOCountryList -> add(800, "UG", "UGA", "Uganda", 0);
$iclISOCountryList -> add(804, "UA", "UKR", "Ukraine", 0);
$iclISOCountryList -> add(581, "UM", "UMI", "United States Minor Outlying Islands", 0);
$iclISOCountryList -> add(858, "UY", "URY", "Uruguay", 0);
$iclISOCountryList -> add(860, "UZ", "UZB", "Uzbekistan", 0);
$iclISOCountryList -> add(336, "VA", "VAT", "Holy See (Vatican City State)", 0);
$iclISOCountryList -> add(670, "VC", "VCT", "Saint Vincent and the Grenadines", 0);
$iclISOCountryList -> add(862, "VE", "VEN", "Venezuela", 0);
$iclISOCountryList -> add(92, "VG", "VGB", "Virgin Islands, British", 0);
$iclISOCountryList -> add(850, "VI", "VIR", "Virgin Islands, U.S.", 0);
$iclISOCountryList -> add(704, "VN", "VNM", "Viet Nam", 0);
$iclISOCountryList -> add(548, "VU", "VUT", "Vanuatu", 0);
$iclISOCountryList -> add(876, "WF", "WLF", "Wallis And Futuna", 0);
$iclISOCountryList -> add(882, "WS", "WSM", "Samoa", 0);
$iclISOCountryList -> add(887, "YE", "YEM", "Yemen", 0);
$iclISOCountryList -> add(710, "ZA", "ZAF", "South Africa", 0);
$iclISOCountryList -> add(894, "ZM", "ZMB", "Zambia", 0);
$iclISOCountryList -> add(716, "ZW", "ZWE", "Zimbabwe", 0);
?>