DROP TABLE IF EXISTS `CubeCart_access_log`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_addressbook`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_admin_log`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_admin_permissions`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_admin_sections`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_admin_sessions`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_admin_users`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_alt_shipping`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_alt_shipping_prices`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_blocker`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_category`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_category_index`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_category_language`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_cats_idx`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_cats_lang`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_config`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_Coupons`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_coupons`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_currencies`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_currency`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_customer`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_customer_group`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_customer_membership`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_docs`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_docs_lang`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_documents`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_Downloads`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_downloads`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_email`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_email_content`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_email_template`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_filemanager`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_geo_country`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_geo_zone`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_history`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_hooks`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_image_index`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_img_idx`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_inventory`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_inventory_language`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_inv_lang`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_iso_counties`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_iso_countries`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_lang`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_lang_strings`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_logo`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_Modules`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_modules`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_newsletter`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_newsletter_subscriber`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_options_bot`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_options_mid`,  `CubeCart_options_top`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_options_set`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_options_set_member`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_options_set_product`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_option_assign`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_option_group`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_option_value`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_order_inv`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_order_inventory`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_order_notes`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_order_sum`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_order_summary`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_order_tax`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_permissions`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_pricing_group`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_pricing_quantity`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_reviews`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_search`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_sessions`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_SpamBot`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_tax_class`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_tax_details`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_tax_rates`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_taxes`; #EOQ 
DROP TABLE IF EXISTS `CubeCart_transactions`; #EOQ